"""add shipsec_number to orders

Revision ID: 91bc87fb146a
Revises: f4b5351c08c8
Create Date: 2025-05-25 22:22:19.851324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bc87fb146a'
down_revision: Union[str, None] = 'f4b5351c08c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('shipsec_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipsec_number')
    # ### end Alembic commands ###
