"""Add address fields to customer and create orders table

Revision ID: c50f1e5403d9
Revises: 
Create Date: 2025-05-21 19:27:20.084029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c50f1e5403d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('address1', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('address2', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('city', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('province', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('country', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('zip', sa.String(), nullable=False))
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_column('customers', 'zip')
    op.drop_column('customers', 'country')
    op.drop_column('customers', 'province')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'address2')
    op.drop_column('customers', 'address1')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###
